[package]
name = "bitcoin-wallet"
version = "1.0.0"
authors = ["Tamas Blummer <tamas.blummer@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/rust-bitcoin/rust-wallet/"
repository = "https://github.com/rust-bitcoin/rust-wallet/"
documentation = "https://github.com/rust-bitcoin/rust-wallet/"
description = "Wallet library for Bitcoin"
keywords = [ "crypto", "bitcoin" ]
readme = "README.md"

[dependencies]
bitcoin = { git= "https://github.com/defiads/rust-bitcoin.git", branch = "patches", features=["serde", "bitcoinconsensus"]}
bitcoin_hashes={version="0.7", features=["serde"]}
secp256k1 = "0.15"
rand="0.7"
rust-crypto = "0.2"
serde = "1"
serde_derive = "1"

[dev-dependencies]
serde_json="1"
hex = "0.3"
